version: '3.8'

networks:
  proxy:
    external:
      name: volcanoproxy_net
services:
  ors-app:
    build:
      context: ./
    container_name: ors-app-local
    ports:
      - "8082:8082"
      - "9001:9001"
    image: openrouteservice/openrouteservice:v8.0.0
    volumes:
      - ./ors-docker:/home/ors
    environment:
      REBUILD_GRAPHS: False
      CONTAINER_LOG_LEVEL: INFO
      XMS: 7g
      XMX: 14g
      ADDITIONAL_JAVA_OPTS: ""
    networks:
      - proxy

  vroom:
    ports:
      - "3000:3000"
    container_name: vroom-express-local
    image: ghcr.io/vroom-project/vroom-docker:v1.14.0
    volumes:
      - $PWD/conf:/conf
    environment:
      VROOM_ROUTER: ors
    # You may need to adjust network_mode according to your requirements.
    # If you need the vroom container to communicate with ors-app, you may need
    # to put them on the same network or define custom networks.
    networks:
      - proxy
